import Head from "next/head";
import styles from "../styles/Home.module.css";
import { gql } from "@apollo/client";
import client from "../lib/apolloClient";
import LinkPost from "../components/Link";
import Navbar from "../components/Navbar";
import { useAuth } from "../lib/auth&post";
import Link from "next/link";
import Modal from "../components/Modal";
import { useState } from "react";

export default function Home({ links, count }) {
  const { isLoggedIn } = useAuth();
  const [modalContent, setModalContent] = useState(null);
  const handleClick = () => {
    setModalContent(null);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>RedditLikePlatform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar count={count} />
      <main className={styles.main}>
        {links?.map((link) => (
          <LinkPost
            key={link.id}
            link={link}
            setModalContent={setModalContent}
          />
        ))}
      </main>
      {modalContent && (
        <Modal modalContent={modalContent} handleClick={handleClick} />
      )}
      {isLoggedIn() && (
        <footer className="footer">
          <Link href="/post">
            <h3>Post a new link</h3>
          </Link>
        </footer>
      )}
    </div>
  );
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query Feed {
        feed {
          count
          links {
            id
            description
            url
            postedBy {
              name
            }
            votes {
              user {
                name
              }
            }
          }
        }
      }
    `,
  });
  return {
    props: {
      links: data.feed.links,
      count: data.feed.count,
    },
  };
}
