import React, { useState } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import { useAuth } from "../lib/auth&post";
import { useRouter } from "next/router";

export default function Login() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const { login, isLoggedIn } = useAuth();
  async function onSubmit(e) {
    e.preventDefault();
    await login({ email, password });
    if (isLoggedIn) {
      await router.push("/");
    }
  }
  return (
    <div className="login">
      <Head>
        <title>RedditLikePlatform Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <form onSubmit={onSubmit} className="login-form">
        <input
          type="email"
          placeholder="email"
          onChange={(e) => setEmail(e.target.value)}
        ></input>
        <input
          type="password"
          placeholder="password"
          onChange={(e) => setPassword(e.target.value)}
        ></input>
        <button type="submit">Login</button>
      </form>
    </div>
  );
}
