import Head from "next/head";
import Navbar from "../components/Navbar";
import { useAuth } from "../lib/auth&post";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Post() {
  const [url, setUrl] = useState("");
  const [description, setDescription] = useState("");

  const router = useRouter();
  const { post } = useAuth();
  async function onSubmit(e) {
    e.preventDefault();
    await post({ url, description });
    await router.push("/");
  }
  return (
    <div className="post">
      <Head>
        <title>RedditLikePlatform Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <form onSubmit={onSubmit} className="post-form">
        <h3>Post a new link</h3>
        <input
          type="url"
          placeholder="url"
          onChange={(e) => setUrl(e.target.value)}
          required
        ></input>
        <textarea
          type="text"
          placeholder="description"
          onChange={(e) => setDescription(e.target.value)}
          required
        ></textarea>
        <button type="submit">Post</button>
      </form>
    </div>
  );
}
