import Head from "next/head";
import Navbar from "../components/Navbar";
import { useState } from "react";
import { useAuth } from "../lib/auth&post";
import { useRouter } from "next/router";

export default function Signup() {
  const router = useRouter();

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const { signup, isLoggedIn } = useAuth();

  async function onSubmit(e) {
    e.preventDefault();
    await signup({ email, password, name });
    if (isLoggedIn) {
      await router.push("/");
    }
  }

  return (
    <div className="signup">
      <Head>
        <title>RedditLikePlatform Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <form onSubmit={onSubmit} className="singup-form">
        <input
          type="text"
          placeholder="name"
          onChange={(e) => setName(e.target.value)}
          required
        ></input>
        <input
          type="email"
          placeholder="email"
          onChange={(e) => setEmail(e.target.value)}
          required
        ></input>
        <input
          type="password"
          placeholder="password"
          onChange={(e) => setPassword(e.target.value)}
          required
        ></input>
        <button type="submit">Sign Up</button>
      </form>
    </div>
  );
}
